hal_402_mgr:  Fix traceback
Sometimes a drive may be in `READY_TO_SWITCH_ON` state when the RESET
button is pressed and a 'stop' command is issued.  That state doesn't
exist in the transition map, causing a `KeyError` and the whole
`hal_402_mgr` component to exit, rendering the robot inoperable
without a restart.

This patch adds all missing states to the disable transition map.

    [INFO] [1596142586.373293] [/hal_402_mgr] [rosout]: hal_402_mgr:  Starting transition 'error' from state 'enabled'
    Traceback (most recent call last):
      File "[...]/src/hal_402_device_mgr/scripts/hal_402_mgr", line 15, in <module>
	hal_402_drives_mgr.run()
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_mgr.py", line 528, in run
	self.manage_errors()
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_mgr.py", line 504, in manage_errors
	self.execute_transition('error')
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_mgr.py", line 298, in execute_transition
	f()
      File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 311, in fn
	self.transition()
      File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 304, in _tran
	self._enter_state(e)
      File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 357, in _enter_state
	return getattr(self, fnname)(e)
      File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 95, in _callback
	return func(obj, *args, **kwargs)
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_mgr.py", line 355, in fsm_in_fault
	self.change_drives(target_path, target_name)
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_mgr.py", line 323, in change_drives
	if self.process_drive_transitions(target_path, target_name):
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_mgr.py", line 379, in process_drive_transitions
	while (not drive.is_transitionable(target_states)) and (
      File "[...]/src/hal_402_device_mgr/src/hal_402_device_mgr/hal_402_drive.py", line 203, in is_transitionable
    [INFO] [1596142586.382157] [/hal_402_mgr] [rosout]: hal_402_mgr: Stopping ...
	transition = self.active_transition_table[self.curr_state][1]
    KeyError: 'READY TO SWITCH ON'
    [INFO] [1596142586.384119] [/hal_402_mgr] [rosout]: hal_402_mgr: Stopped